### ISSUE TITLE
Sidebar "Files" not recognizable enough

### ISSUE THREAD

**Issue by blacksheepaul** [dhay3/bios-typora-theme#1]
Very nice theme bro, but I wish it could be light when in "Files" sidebar

![image](https://github.com/user-attachments/assets/babeb86a-4302-47d0-9538-9501aa4aa119)

**Comment by dhay3** [comment]
@guluguru Thanks for you mention that, I've fixed this issue and add some style to "Files" sidebar.

here is the demonstration:

![image](https://github.com/user-attachments/assets/e5f39587-209e-46a4-a89c-69ac24600b27)
